[package]
name = "playground"
version = "0.1.0"
authors = ["Ben Mitchell <dezyh@outlook.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "comparisons"
harness = false
